# environment.yaml
name: archx
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - graphviz
  - python-graphviz
  - loguru
  - matplotlib
  - numpy
  - ortools
  - pandas
  - Pillow
  - pyfiglet
  - pyyaml
  - yamlordereddictloader
  - pytest
  - pytest-cov
  - maturin>=1.5
  - pip