architecture:
  attribute:
    frequency: 1000
    interface: chiplet_cmos
    technology: 7
  module:
    dram:
      instance:
      - 1
      query:
        bandwidth: 256
        class: dram
        interface: cacti7
        size: 8589934592
        technology: 45
      tag:
      - offchip
      - memory
    ififo:
      instance:
      - 512
      query:
        class: fifo_sync_tsmc
        depth: 512
        width: 16
      tag:
      - onchip
      - fifo
      - array
    isram:
      instance:
      - 1
      query:
        bank: 1024
        class: sram
        depth: 1536
        interface: cacti7
        technology: 45
        width: 16
      tag:
      - memory
    ofifo:
      instance:
      - 512
      query:
        class: fifo_sync_tsmc
        depth: 512
        width: 16
      tag:
      - onchip
      - fifo
      - array
    osram:
      instance:
      - 1
      query:
        bank: 1024
        class: sram
        depth: 5120
        interface: cacti7
        technology: 45
        width: 16
      tag:
      - memory
    output_adder:
      instance:
      - 512
      query:
        class: fp16_adder_tsmc
      tag:
      - onchip
      - output_adder
      - array
    pe:
      instance:
      - 512
      - 512
      query:
        class: pe_tsmc
      tag:
      - onchip
      - array
      - compute
    weight_en_reg:
      instance:
      - 512
      - 512
      query:
        class: register_tsmc
        width: 1
      tag:
      - onchip
      - register
      - control
      - array
    weight_path_en_reg:
      instance:
      - 512
      - 512
      query:
        class: register_tsmc
        width: 1
      tag:
      - onchip
      - register
      - control
      - array
    weight_path_reg:
      instance:
      - 512
      - 512
      query:
        class: register_tsmc
        width: 16
      tag:
      - onchip
      - register
      - array
    weight_reg:
      instance:
      - 512
      - 512
      query:
        class: register_tsmc
        width: 16
      tag:
      - onchip
      - register
      - array
    wfifo:
      instance:
      - 512
      query:
        class: fifo_sync_tsmc
        depth: 512
        width: 16
      tag:
      - onchip
      - fifo
      - array
    wsram:
      instance:
      - 1
      query:
        bank: 1024
        class: sram
        depth: 5120
        interface: cacti7
        technology: 45
        width: 16
      tag:
      - memory
