workload:
  configuration:
    batch_size: 128
    dim: 4096
    heads: 32
    hidden_dim: 14336
    kv_heads: 8
    layers: 32
    max_seq_len: 8192
    prefill_seq_len: 64
    vocab_size: 128256
  name: llama_3_8b
