architecture:
  attribute:
    frequency: 400
    interface: csv_cmos
    technology: 45
  module:
    adder:
      instance:
      - 8
      query:
        class: adder_bfloat16
      tag:
      - array
    and_gate:
      instance:
      - 8
      - 8
      query:
        class: and_gate
        width: 16
      tag:
      - array
    comparator:
      instance:
      - 8
      query:
        class: comparator
        width: 4
      tag:
      - array
    counter:
      instance:
      - 1
      query:
        class: counter
        width: 3
      tag:
      - array
    counter_register:
      instance:
      - 1
      query:
        class: register
        width: 3
      tag:
      - array
    dram:
      instance:
      - 1
      query:
        bandwidth: 128
        class: dram
        interface: cacti7
        size: 8589934592
      tag:
      - memory
    exp_clamp:
      instance:
      - 8
      query:
        class: vlp_clamp
      tag:
      - array
    exp_norm:
      instance:
      - 8
      query:
        class: exp_norm
      tag:
      - array
    exp_select:
      instance:
      - 8
      query:
        class: exp_select
      tag:
      - array
    exponent_register:
      instance:
      - 8
      query:
        class: register
        width: 8
      tag:
      - array
    ififo:
      instance:
      - 8
      query:
        class: fifo
        depth: 8
        width: 16
      tag:
      - array
    imux:
      instance:
      - 1
      query:
        class: mux
        inputs: 2
        width: 128
      tag:
      - array
    isram:
      instance:
      - 1
      query:
        bank: 4
        class: sram
        depth: 1024
        interface: cacti7
        width: 128
      tag:
      - memory
    magnitude_register:
      instance:
      - 8
      query:
        class: register
        width: 3
      tag:
      - array
    min_max_tree:
      instance:
      - 7
      query:
        class: vlp_max_min
      tag:
      - array
    min_max_tree_register:
      instance:
      - 1
      query:
        class: register
        width: 8
      tag:
      - array
    multiplier:
      instance:
      - 8
      query:
        class: multiplier_bfloat16
      tag:
      - array
    multiplier_register:
      instance:
      - 8
      query:
        class: register
        width: 16
      tag:
      - array
    multiplier_vector:
      instance:
      - 1
      query:
        class: multiplier_bfloat16
      tag:
      - array
    ofifo:
      instance:
      - 8
      query:
        class: fifo
        depth: 2
        width: 16
      tag:
      - array
    or_gate:
      instance:
      - 8
      - 8
      - 2
      query:
        class: or_gate
        width: 16
      tag:
      - array
    osram:
      instance:
      - 1
      query:
        bank: 4
        class: sram
        depth: 1024
        interface: cacti7
        width: 128
      tag:
      - memory
    pe_fifo:
      instance:
      - 8
      query:
        class: fifo
        depth: 8
        width: 16
      tag:
      - array
    register_vector:
      instance:
      - 1
      query:
        class: register
        width: 16
      tag:
      - array
    round:
      instance:
      - 8
      query:
        class: vlp_round
      tag:
      - array
    sign_fifo:
      instance:
      - 8
      query:
        class: fifo
        depth: 2
        width: 1
      tag:
      - array
    sign_mantissa_register:
      instance:
      - 8
      query:
        class: register
        width: 4
      tag:
      - array
    sign_register:
      instance:
      - 8
      query:
        class: register
        width: 1
      tag:
      - array
    sign_xor:
      instance:
      - 8
      query:
        class: xor_bitwise
        width: 1
      tag:
      - array
    temporal_register:
      instance:
      - 8
      - 8
      query:
        class: register
        width: 1
      tag:
      - array
    wfifo:
      instance:
      - 8
      query:
        class: fifo
        depth: 2
        width: 4
      tag:
      - array
    window_select:
      instance:
      - 1
      query:
        class: vlp_window
      tag:
      - array
    wmux:
      instance:
      - 1
      query:
        class: mux
        inputs: 2
        width: 32
      tag:
      - array
    wsram:
      instance:
      - 1
      query:
        bank: 4
        class: sram
        depth: 1024
        interface: cacti7
        width: 128
      tag:
      - memory
