adder:
  WIDTH: 32
ACCUMULATOR_BFLOAT16_REG:
AND_BITWISE:
  WIDTH: 1
CH_ALOC:
CH_DEALOC:
COMPARATOR:
  WIDTH: 1
DECODER:
DOUBLE_INPUT_FIFO:
  WIDTH: 16
  depth: 8
EXP_NORM:
FIFO:
  WIDTH: 16
  depth: 8
INT_TO_BF16:
INT_TO_FP:
MULTIPLEXER:
  WIDTH: 16
  NUM_INPUTS: 2
MULTIPLIER_BFLOAT16_REG:
OR_BITWISE:
  WIDTH: 1
PREALIGNER:
PWL_22_SEG_ENCODER:
PWL_BF_MAX:
REGISTER:
  WIDTH: 1
VLP_CLAMP:
VLP_COUNTER:
  WIDTH: 3
VLP_MAX:
  WIDTH: 4
VLP_MAX_MIN:
  WIDTH: 4
VLP_MIN:
  WIDTH: 4
VLP_ROUND:
VLP_WINDOW:
XNOR_BITWISE:
  WIDTH: 1
XOR_BITWISE:
  WIDTH: 1